"""Centralized thresholds for retrieval and QA decisions."""

ANCHOR_CONFIDENCE_STRONG: float = 0.80
ANCHOR_CONFIDENCE_WEAK: float = 0.60
ANCHOR_CONFIDENCE_DEGRADE: float = 0.40
ANCHOR_NAME_MATCH_EXACT: float = 0.85
ANCHOR_NAME_MATCH_AMBIGUOUS: float = 0.65
ANCHOR_INHERIT_DECAY: float = 0.90
FOLLOW_UP_MAX_TOKENS: int = 12
RETRIEVAL_CONCENTRATION: float = 0.55
RETRIEVAL_CONCENTRATION_ENHANCED: float = 0.45
RETRIEVAL_CONCENTRATION_DEGRADE: float = 0.35
EVIDENCE_SUFFICIENT: float = 0.60
EVIDENCE_ENHANCEMENT: float = 0.40
EXPANSION_GAIN: float = 0.25
RESULT_CONSISTENCY: float = 0.40
METRICS_TOP_K: int = 5
EVIDENCE_REQUIRED_THRESHOLD: float = 2.0
EVIDENCE_RELEVANCE_THRESHOLD: float = 0.55
